settings:
  title: 'Solarsens Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: api # unique identifier
    name: API
    description: 'The brain' # default=empty
    url: 'https://solarsens.avaasia.co/api2/version' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: Frontend
    name: Web Portal
    description: 'Solarsens web portal'
    url: 'https://solarsens.avaasia.co/en'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true # allows the title to be a link, default=true

  - id: thingsboard
    name: Data Acq Server
    url: 'https://monitoring.avaasia.co/api/user/devices'
    method: GET
    expectStatus: 401
    
  - id: thingsboard2
    name: Data Acq Server2
    url: 'https://gs-monitoring.avaasia.co/api/user/devices'
    method: GET
    expectStatus: 401
